### PR TITLE
Add secret-from-env to initContainer

### LINKED ISSUE #6: initContainer does not read environment from secret
**Describe the bug**
When building inside a secure network, one needs to present http_proxy variables to the container in order to connect. Such variables might have credentials to authenticate against the proxy, hence the need to be stored as secrets.
When using the *environment-from-secret* configuration, I expected the variables to be made available to the initContainer as well.

**To Reproduce**
1. create secret 
kubectl create secret generic my-secret --from-literal=http_proxy=http://user:password@my.proxy

2. add *environment-from-secret: my-secret* to pipeline.yaml
3. job times out waiting for checking-out code

**Expected behavior**
Job should run to completion.

### PR DESCRIPTION
**Pull request by boufleur**
Trying to fix https://github.com/EmbarkStudios/k8s-buildkite-plugin/issues/6

### CODE REVIEW

**Review by iffyio — CHANGES_REQUESTED** [review]
Hi @boufleur Thanks for tackling this and sorry about the delayed response :disappointed: 

Since the init container is something the user shouldn't really notice/care-about, it might make more sense to make this feature opt-in to avoid surprises, so that e.g the environment variable names from the secret do not unintentionally conflict with any that the init container uses now or in the future.
One way we could achieve this would be to add a new option. say `init-environment-from-secret` which serves the same function as `environment-from-secret` but applies only to the init container.
What do you think? Would you be able to continue with this PR?

**Comment by boufleur** [comment]
Hi @iffyio, I agree. I'll update my PR.

**Review by iffyio — APPROVED** [review]
Awesome! :star:

**Comment by iffyio** [comment]
This has gone into the 1.2.7 release `EmbarkStudios/k8s#1.2.7`
Thanks for the changes @boufleur!

**Pull request merged**
