### PR TITLE
Added External Secrets Support (cont.)

### PR DESCRIPTION
**Pull request by clbx**
A continuation of #68 that does not come off our main branch.

### CODE REVIEW

**Comment by tgolsson** [comment]
OK; pinky promise will get to this tomorrow! All ready to go @clbx? :D

**Comment by clbx** [comment]
We've been using it pretty heavily in our pipelines and its been working great. 

I misnamed the ClusterSecretStore type at some point between my testing and the final result, but that is fixed. This is what my most recent commit fixed. 

I believe that it is all ready to go, and if any issues come up during our use, I will contribute them back upstream.

**Comment by tgolsson** [comment]
Thanks! 

I've never figured out how to do buildkite builds for forks so pushed an in-org branch and built here: 
https://buildkite.com/embark-studios/k8s-buildkite-plugin/builds/274#0187a44f-33ad-49ba-b59c-85fffb375b51

Looks like a bunch of shellcheck issues that'd be lovely if you could fix them and then I'll merge :-)

**Comment by clbx** [comment]
I will take a look at them on Monday

**Comment by clbx** [comment]
I completely forgot about this PR, I put it in our next sprint to finish these up so we can merge this in.

**Comment by clbx** [comment]
I can't run the CI to check, but I believe I fixed them. 

In case you had any remaining worries about stability and functionality we've migrated all of our pipelines over to using this plugin and its been working flawlessly for the past 4 or 5 months.

**Comment by tgolsson** [comment]
@clbx There's still some missing -- I tried to push a fix to this branch but I don't think you've granted maintainer push permissions on this PR. https://github.com/EmbarkStudios/k8s-buildkite-plugin/commit/216e8fb909a93f735f75c912271f05515def0107 is the missing fixes :-)

**Comment by clbx** [comment]
I dont work for greymatter anymore as of Friday, so I also no longer have push permissions to the repository. Someone who does will have to fix the last few changes. @moosecanswim @joshuaswickirl I guess I missed a few

**Comment by tgolsson** [comment]
Ah; I can just merge it from my branch tomorrow then, let's not make life overly complicated. And good luck on your new adventure @clbx! :-)

**Comment by clbx** [comment]
Thank you, I'm glad I was able to contribute to this even if it has taken months to get it in 😆

**Comment by joshuaswickirl** [comment]
@tgolsson can we close this pr then?

**Comment by tgolsson** [comment]
Back from vacation now, merged in #72!

**Pull request closed without merging**
