### PR TITLE
allow for skipping the bootstrap container step

### PR DESCRIPTION
**Pull request by 0ax1**
Allow for skipping the bootstrap container step such that workloads without an init container can be executed.

### CODE REVIEW

**Comment by webbju** [comment]
Difficult to explain how I would approach this differently; so made a branch off yours instead: 
https://github.com/EmbarkStudios/k8s-buildkite-plugin/compare/webbju/make-bootstrap-step-optional?expand=1

Your solution would require us to have both a `skip-bootstrap-container-step` and a patch which removed `initContainers`. I noticed that `BUILDKITE_PLUGIN_K8S_INIT_IMAGE` is a customizable option anyway.

**Comment by iffyio** [comment]
I think it makes sense to reuse the `BUILDKITE_PLUGIN_K8S_INIT_IMAGE` option indeed, @0ax1 can we use that here? then we can mention in that [option's documentation](https://github.com/EmbarkStudios/k8s-buildkite-plugin#init-image-optional-string) that if its set to empty string then no init container is used

**Comment by 0ax1** [comment]
> I think it makes sense to reuse the `BUILDKITE_PLUGIN_K8S_INIT_IMAGE` option indeed, @0ax1 can we use that here? then we can mention in that [option's documentation](https://github.com/EmbarkStudios/k8s-buildkite-plugin#init-image-optional-string) that if its set to empty string then no init container is used

Agreed, that's cleaner. Updating the PR.

**Comment by 0ax1** [comment]
@webbju @iffyio ready for review.

**Review by iffyio — APPROVED** [review]
LGTM!

**Review by webbju — APPROVED** [review]
LGTM also.

**Pull request merged**
