### PR TITLE
Add more buildkite passthrough variables

### PR DESCRIPTION
**Pull request by keith**
This also sorts and removes some duplicates from this list

### CODE REVIEW

**Review by Bencodes — APPROVED** [review]
Any reason we don't just pass along anything with the buildkite prefix?

**Comment by keith** [comment]
it probably should

**Review by iffyio — APPROVED** [review]

**Comment by iffyio** [comment]
> Any reason we don't just pass along anything with the buildkite prefix?

Yeah I'm thinking that would be reasonable to do!

**Comment by keith** [comment]
Thanks!

**Pull request merged**
